---
- name: Ensure .kube directory exists.
  file:
    path: ~/.kube
    state: directory
    mode: 0755

- name: Join Print kubernetes bootstrap token.
  debug:
    var: kubernetes_bootstrap_token

- name: Join Print kubernetes certificate
  debug:
    var: kubernetes_init_certificate_key

- name: Add Kubernetes control plane join configuration.
  template:
    src: kubeadm-master-join-config.j2
    dest: ~/.kube/kubeadm-master-join.yml
    mode: 0644

- name: Pull core kubernetes images.
  command: kubeadm config images pull

- name: Join contol plane node to the cluster.
  command: kubeadm join --config ~/.kube/kubeadm-master-join.yml
  register: kubeadm_control_node_join

- name: Symlink the kubectl admin.conf to ~/.kube/conf.
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
    mode: 0644

- name: Print the init output to screen.
  debug:
    var: kubeadm_control_node_join.stdout
  when: not kubernetes_init_stat.stat.exists